version: '3.8'



services:
  web:
    image: app-name:projectA_app
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel


  db:
    platform: "linux/amd64"
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
     - "3309:3306"
    networks:
      - laravel
    volumes:
      - dbdata:/var/lib/mysql

networks:
  laravel:
    driver: bridge


volumes:
  dbdata:

